package com.helishop.core.persistence;

import com.helishop.core.common.constants.ProductStatus;
import com.helishop.core.common.constants.ShopStatus;
import com.helishop.core.common.constants.UserRole;
import com.helishop.core.common.constants.UserStatus;
import com.helishop.core.config.JpaAuditingConfig;
import com.helishop.core.modules.product.entity.Category;
import com.helishop.core.modules.product.entity.Product;
import com.helishop.core.modules.product.entity.ProductSku;
import com.helishop.core.modules.product.repository.CategoryRepository;
import com.helishop.core.modules.product.repository.ProductRepository;
import com.helishop.core.modules.product.repository.ProductSkuRepository;
import com.helishop.core.modules.user.entity.Shop;
import com.helishop.core.modules.user.entity.User;
import com.helishop.core.modules.user.repository.ShopRepository;
import com.helishop.core.modules.user.repository.UserRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@Import(JpaAuditingConfig.class)
class UserPersistenceTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ShopRepository shopRepository;

    @Autowired
    private CategoryRepository categoryRepository;

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private ProductSkuRepository productSkuRepository;

    @Test
    @DisplayName("Lưu User thành công, ID sinh tự động và createdAt / updatedAt không null nhờ JPA Auditing")
    void shouldPersistUserWithAutoGeneratedIdAndAuditingTimestamps() {
        // Arrange
        User user = User.builder()
                .email("nguyenvana@example.com")
                .passwordHash("$2a$12$e8wY0P4sC9...")
                .fullName("Nguyễn Văn A")
                .phone("0912345678")
                .role(UserRole.ROLE_CUSTOMER)
                .status(UserStatus.ACTIVE)
                .build();

        // Act
        User savedUser = userRepository.saveAndFlush(user);

        // Assert
        assertThat(savedUser.getId()).isNotNull();
        assertThat(savedUser.getId()).isPositive();
        assertThat(savedUser.getCreatedAt()).isNotNull();
        assertThat(savedUser.getUpdatedAt()).isNotNull();
        assertThat(savedUser.getCreatedAt()).isBeforeOrEqualTo(LocalDateTime.now());
        assertThat(savedUser.getEmail()).isEqualTo("nguyenvana@example.com");
        assertThat(savedUser.getRole()).isEqualTo(UserRole.ROLE_CUSTOMER);
        assertThat(savedUser.getStatus()).isEqualTo(UserStatus.ACTIVE);
    }

    @Test
    @DisplayName("Lưu ProductSku thành công với khóa lạc quan @Version được khởi tạo = 0")
    void shouldPersistProductSkuWithOptimisticLockingVersionZero() {
        // 1. Tạo User chủ shop
        User seller = userRepository.saveAndFlush(User.builder()
                .email("seller@eshop.com")
                .passwordHash("hash123")
                .fullName("Chủ Shop A")
                .phone("0987654321")
                .role(UserRole.ROLE_SELLER)
                .status(UserStatus.ACTIVE)
                .build());

        // 2. Tạo Shop
        Shop shop = shopRepository.saveAndFlush(Shop.builder()
                .owner(seller)
                .shopName("Official Tech Store")
                .description("Cửa hàng công nghệ chính hãng")
                .status(ShopStatus.ACTIVE)
                .rating(BigDecimal.valueOf(4.85))
                .build());

        // 3. Tạo Category
        Category category = categoryRepository.saveAndFlush(Category.builder()
                .name("Điện thoại & Phụ kiện")
                .slug("dien-thoai-phu-kien")
                .level(1)
                .build());

        // 4. Tạo Product
        Product product = productRepository.saveAndFlush(Product.builder()
                .shop(shop)
                .category(category)
                .name("iPhone 15 Pro Max")
                .slug("iphone-15-pro-max")
                .description("Flagship Apple 2024")
                .status(ProductStatus.ACTIVE)
                .build());

        // 5. Tạo ProductSku với stockQuantity và version
        ProductSku sku = ProductSku.builder()
                .product(product)
                .skuCode("IP15PM-256-NAT")
                .price(BigDecimal.valueOf(29990000))
                .originalPrice(BigDecimal.valueOf(34990000))
                .stockQuantity(50)
                .skuAttributes("Color: Natural Titanium, Storage: 256GB")
                .build();

        ProductSku savedSku = productSkuRepository.saveAndFlush(sku);

        // Assert
        assertThat(savedSku.getId()).isNotNull();
        assertThat(savedSku.getVersion()).isEqualTo(0L);
        assertThat(savedSku.getStockQuantity()).isEqualTo(50);
        assertThat(savedSku.getCreatedAt()).isNotNull();
        assertThat(savedSku.getUpdatedAt()).isNotNull();
        assertThat(savedSku.getProduct().getId()).isEqualTo(product.getId());
    }
}
